# Generated by Django 4.0.3 on 2022-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pics', '0002_alter_photo_options_remove_photo_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
    ]
