# Generated by Django 4.0.3 on 2022-04-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pics', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='height',
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
