# Generated by Django 4.0.3 on 2022-04-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pics', '0004_remove_photo_height_alter_photo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
